{"result": {"folders": ["labx", "quiz1", "lab0"], "nr": 540, "data": {"embed_links": []}, "created": "2015-11-06T17:24:23Z", "bucket_order": 3, "no_answer_followup": 0, "change_log": [{"uid": "ig2g4wrcoZE", "anon": "no", "when": "2015-11-06T17:24:23Z", "data": "ignxmck0fqv6ui", "type": "create"}, {"to": "ignxmcjxagr6uh", "uid": "iarg675erpdrg", "anon": "no", "when": "2015-11-07T04:42:42Z", "data": "igoluoj99uz6xp", "type": "s_answer"}, {"to": "ignxmcjxagr6uh", "uid": "i6q7xxh4f9y24h", "anon": "no", "when": "2015-11-11T10:13:02Z", "data": "igunewb2mk64cj", "type": "i_answer"}], "bucket_name": "Today", "history": [{"anon": "no", "uid": "ig2g4wrcoZE", "subject": "create docker failed", "created": "2015-11-06T17:24:23Z", "content": "<p></p><div>\n<div>\n<div>\n<div>\n<div>\n<div>\n<div>Error: {&#34;explanation&#34;: &#34;The server has either erred or is incapable of performing the requested operation.&#34;, &#34;code&#34;: 500, &#34;error&#34;: {&#34;message&#34;: &#34;Remote error: TimeoutError QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30\\n[u&#39;Traceback (most recent call last):\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/oslo/messaging/rpc/dispatcher.py\\&#34;, line 134, in _dispatch_and_reply\\\\n incoming.message))\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/oslo/messaging/rpc/dispatcher.py\\&#34;, line 177, in _dispatch\\\\n return self._do_dispatch(endpoint, method, ctxt, args)\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/oslo/messaging/rpc/dispatcher.py\\&#34;, line 123, in _do_dispatch\\\\n result = getattr(endpoint, method)(ctxt, **new_args)\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/heat/engine/service.py\\&#34;, line 69, in wrapped\\\\n return func(self, ctx, *args, **kwargs)\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/heat/engine/service.py\\&#34;, line 637, in create_stack\\\\n owner_id)\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/heat/engine/service.py\\&#34;, line 544, in _parse_template_and_validate_stack\\\\n self._validate_new_stack(cnxt, stack_name, tmpl)\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/heat/engine/service.py\\&#34;, line 527, in _validate_new_stack\\\\n if db_api.stack_get_by_name(cnxt, stack_name):\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/heat/db/api.py\\&#34;, line 122, in stack_get_by_name\\\\n return IMPL.stack_get_by_name(context, stack_name)\\\\n&#39;, u&#39; File \\&#34;/usr/lib/python2.6/site-packages/heat/db/sqlalchemy/api.py\\&#34;, line 281, in stack_get_by_name\\\\n return query.first()\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/query.py\\&#34;, line 2282, in first\\\\n ret = list(self[0:1])\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/query.py\\&#34;, line 2149, in __getitem__\\\\n return list(res)\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/query.py\\&#34;, line 2353, in __iter__\\\\n return self._execute_and_instances(context)\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/query.py\\&#34;, line 2366, in _execute_and_instances\\\\n close_with_result=True)\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/query.py\\&#34;, line 2357, in _connection_from_session\\\\n **kw)\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py\\&#34;, line 799, in connection\\\\n close_with_result=close_with_result)\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py\\&#34;, line 805, in _connection_for_bind\\\\n return engine.contextual_connect(**kwargs)\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py\\&#34;, line 1661, in contextual_connect\\\\n self.pool.connect(),\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/pool.py\\&#34;, line 272, in connect\\\\n return _ConnectionFairy(self).checkout()\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/pool.py\\&#34;, line 431, in __init__\\\\n rec = self._connection_record = pool._do_get()\\\\n&#39;, u&#39; File \\&#34;/usr/lib64/python2.6/site-packages/sqlalchemy/pool.py\\&#34;, line 768, in _do_get\\\\n (self.size(), self.overflow(), self._timeout))\\\\n&#39;, u&#39;TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30\\\\n&#39;].&#34;, &#34;traceback&#34;: null, &#34;type&#34;: &#34;RemoteError&#34;}, &#34;title&#34;: &#34;Internal Server Error&#34;}</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>"}], "type": "question", "tags": ["lab0", "labx", "quiz1", "student"], "tag_good": [{"role": "student", "name": "毛昂", "endorser": {}, "admin": false, "photo": null, "id": "iz3x1nsaKp6", "photo_url": null, "published": true, "us": false, "facebook_id": null}], "unique_views": 194, "children": [{"folders": [], "data": {"embed_links": []}, "children": [], "created": "2015-11-07T04:42:42Z", "bucket_order": 3, "tag_endorse": [], "bucket_name": "Today", "id": "igoluoj7gfd6xo", "history": [{"anon": "no", "uid": "iarg675erpdrg", "subject": "", "created": "2015-11-07T04:42:42Z", "content": "我也是这样。"}], "type": "s_answer", "tag_endorse_arr": [], "config": {}, "is_tag_endorse": false}, {"folders": [], "data": {"embed_links": []}, "children": [], "created": "2015-11-11T10:13:02Z", "bucket_order": 3, "tag_endorse": [], "bucket_name": "Today", "id": "igunewb0iuz4ci", "history": [{"anon": "no", "uid": "i6q7xxh4f9y24h", "subject": "", "created": "2015-11-11T10:13:02Z", "content": "<p>可能是那个时段的IBM的机器出了点问题,我现在试没问题&#xff0c;遇到创建失败&#xff0c;然后理由一大堆的的时候可以点击删除&#xff0c;然后重新创建。。。</p>"}], "type": "i_answer", "tag_endorse_arr": [], "config": {}, "is_tag_endorse": false}], "tag_good_arr": ["iz3x1nsaKp6"], "no_answer": 0, "id": "ignxmcjxagr6uh", "config": {}, "status": "active", "drafts": null, "request_instructor": 0, "request_instructor_me": false, "bookmarked": 5, "num_favorites": 0, "my_favorite": false, "is_bookmarked": false, "is_tag_good": false, "q_edits": [], "i_edits": [], "s_edits": [], "t": 1643168001664, "default_anonymity": "no"}, "error": null, "aid": "kyuzswhsntj4hl"}